travis:
  secure:
    BINSTAR_TOKEN: JsSv/EI5ImkSDKzvqYGIJsf6+tVPsk59KPqJLZyq/EyaB6X17tfGAFWrZPoa/IkeKUoHaWHBJ0taR76WOrgk4pIkZq9+5Vj5cH2TnHVxQPsID6rVtHh0YW1n2fNUxl9gAzRE18/ElkYxyUoChdhKo042EPA22YggfEHYMyEAdhs95NRRLGIk6YrjHQCyzpIB2phdRY9quUL3qX4pl3lco4L0wU0WMl8j0qbkaj1EBbWXWkzzRDJkmtx6TiYBmHSG6lwNvFeuQEbBWDqV2kcXkxiV49zMXgaQIfUQyvGOQ06DSliYPgM1QhxQxbvgKsk8UhdpgkIEwrYzuWrOp0LfekRjOwn15iyWdAXE/HVY77/wOEqtDGjjfcjDWIuHrpXfopteDW2O0MXcCfsvCya0+otRDHqWV2cpZ6fRQBNjIXx9Dyr+aP05GRaL5t4cgqyOek7e9HFhQTHtiYbswGzinqY4gPPMK0cM8hJ7G78VOvZcNSI2SKLhV0zq1vbJjaGTkp6viKVLDvhy2rS5YEqxQLjDUlFac6d5jFawg3DqRNBNwrdaI4BW33xo19jNjncnYDFjSvmJ4spoI3gWfwFGQX28wxrW1vdeVHp5tbYtHrQmvrciT2LgyMZIDdk8Qq26M0//Zje8jH+IE9JYU0RMWHbRoBwnxlO7YTnRVJgDfb8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
