travis:
  secure:
    BINSTAR_TOKEN: DyjIFqrfuJuJK/RemD1PRmCfWpirICuBcSxZfLj+ajwaoV9eAHWS95tsD4CiqMkDqY1c+qnl2QVaZRInp7JiKAKoo2s0Mi+ay6pXDlKtqiBiJrYZMr0erdwMsWRclBlyt/XjOIBVnh/wPNxSNzfnoZ16bEpBcuhiSmZNZwMzgd0EzUGY/VzgQSEctYPUQAoBGdagAH8PMklhKiHxw5vn7L/lnVV7NoZQQ4vhT9g0jz7wrI9tddVG/d79z6Z7sJn0KJl5o0oSf8JNg4S1FrqjvLLyfj2F+qsMB0wb+s1RRucwuhasfcd61/GHbbLU4TMrQtsi0zlEpfz6UT8VWM+QeILm0wQkb6q+G6WDyWVSK7l3tjQXAUkqclcsf9099C731UZ636U5sc8ZmeRaVPkPzETWcjbVRZ+lUAyqDyX8ec3L34v86xWwHdEK8xkTV2nTmHGOFLYLmNgjrj9X92vlZQfO2D3Qazpiyfetvt0sloyl4GMuymT20MOJqCs7ecUP6ZGiJZoWg3dgDJTdrBzdP+J3b78y5XTvYcMNTRrR33QimYYCjU5ZtT1az2hVYyS4qdh0R184i7THjSamaVyn9eM5LDtHU9rq0CfMnvg5Fcwy8XoXBk6acvDxCaFlJjQjaIeVkzunZgJD2/qqM8c1PdIK7BED7E1VVCa48NQRvYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
